"""add operate record table

Revision ID: 3136b0f376d2
Revises: 4dfa947b50c7
Create Date: 2021-10-17 17:00:56.263296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3136b0f376d2'
down_revision = '4dfa947b50c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operate_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('operate_user', sa.String(length=16), nullable=False, comment='操作人'),
    sa.Column('event', sa.String(length=256), nullable=False, comment='操作事件'),
    sa.ForeignKeyConstraint(['operate_user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='管理员操作事件记录表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operate_record')
    # ### end Alembic commands ###
