"""init db

Revision ID: 3383fee1a26a
Revises: 
Create Date: 2021-09-28 15:00:55.712108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3383fee1a26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('role_name', sa.String(length=16), nullable=False, comment='角色名称'),
    sa.Column('role_desc', sa.String(length=32), nullable=False, comment='角色描述'),
    sa.Column('upload', sa.Boolean(), nullable=False, comment='上传权限'),
    sa.Column('delete', sa.Boolean(), nullable=False, comment='删除权限'),
    sa.Column('user_manage', sa.Boolean(), nullable=False, comment='用户管理权限'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='角色是否被禁用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    comment='用户角色权限表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('username', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=32), nullable=False, comment='用户昵称'),
    sa.Column('email', sa.String(length=32), nullable=False, comment='用户邮箱'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='用户密码hash值'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='用户角色'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='用户是否被禁用'),
    sa.ForeignKeyConstraint(['role'], ['role.role_name'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户信息表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
