"""add upload download table

Revision ID: 4dfa947b50c7
Revises: 3383fee1a26a
Create Date: 2021-10-13 15:52:50.629471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfa947b50c7'
down_revision = '3383fee1a26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('download_ip', sa.String(length=128), nullable=False, comment='下载用户IP'),
    sa.Column('package', sa.String(length=256), nullable=False, comment='下载的包名'),
    sa.Column('client', sa.String(length=128), nullable=False, comment='下载客户端名称'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户下载记录表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('upload_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('upload_user', sa.String(length=16), nullable=False, comment='上传用户'),
    sa.Column('package', sa.String(length=256), nullable=False, comment='Python包名称'),
    sa.ForeignKeyConstraint(['upload_user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户上传记录表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_upload_record_package'), 'upload_record', ['package'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_record_package'), table_name='upload_record')
    op.drop_table('upload_record')
    op.drop_table('download_record')
    # ### end Alembic commands ###
