"""init db

Revision ID: 7d211b59573c
Revises: 
Create Date: 2021-09-27 18:00:02.169897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d211b59573c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('username', sa.String(length=16), nullable=True, comment='用户名'),
    sa.Column('nickname', sa.String(length=32), nullable=False, comment='用户昵称'),
    sa.Column('email', sa.String(length=32), nullable=False, comment='用户邮箱'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='用户密码hash值'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户信息表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
