"""init db

Revision ID: c06dbe4f66e4
Revises: 
Create Date: 2021-10-18 16:31:03.467180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06dbe4f66e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('download_ip', sa.String(length=32), nullable=False, comment='下载用户IP'),
    sa.Column('package', sa.String(length=256), nullable=False, comment='包名'),
    sa.Column('client', sa.String(length=512), nullable=False, comment='客户端信息'),
    sa.Column('download_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_ip', 'package', 'download_datetime', name='uk_download'),
    comment='用户下载记录表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('role_name', sa.String(length=16), nullable=False, comment='角色名称'),
    sa.Column('role_desc', sa.String(length=32), nullable=False, comment='角色描述'),
    sa.Column('upload', sa.Boolean(), nullable=False, comment='上传权限'),
    sa.Column('delete', sa.Boolean(), nullable=False, comment='删除权限'),
    sa.Column('user_manage', sa.Boolean(), nullable=False, comment='用户管理权限'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='角色是否被禁用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    comment='用户角色权限表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('username', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=32), nullable=False, comment='用户昵称'),
    sa.Column('email', sa.String(length=32), nullable=False, comment='用户邮箱'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='用户密码hash值'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='用户角色'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='用户是否被禁用'),
    sa.ForeignKeyConstraint(['role'], ['role.role_name'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户信息表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('operate_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('operate_user', sa.String(length=16), nullable=False, comment='操作人'),
    sa.Column('event', sa.String(length=512), nullable=False, comment='操作事件'),
    sa.ForeignKeyConstraint(['operate_user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='管理员操作事件记录表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('upload_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('upload_user', sa.String(length=16), nullable=False, comment='上传用户'),
    sa.Column('package', sa.String(length=256), nullable=False, comment='Python包名称'),
    sa.ForeignKeyConstraint(['upload_user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户上传记录表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_upload_record_package'), 'upload_record', ['package'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_record_package'), table_name='upload_record')
    op.drop_table('upload_record')
    op.drop_table('operate_record')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('download_record')
    # ### end Alembic commands ###
